# Exception Handling

# try except

number_tree = 5
number_four = 1

number_four = "1"

try:
    print(number_tree + number_four)
    print("No se ha producido un error")
except:
    print("Se ha producido un error")